# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10

    active_opacity = 0.96
    inactive_opacity = 0.80

    dim_inactive = true
    dim_strength = 0.3

    blur {
        enabled = false
    }
}

general {
    col.active_border = rgba(ff0000ff) rgba(ff8800ff) rgba(ffff00ff) rgba(00ff44ff) rgba(00aaffff) rgba(8844ffff) rgba(ff00aaff) rgba(ff0000ff) 0deg
    col.inactive_border = rgba(33333388)
    border_size = 2
}


# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
