$color = rgba(3, 0, 0, 1)
$inner_color = rgba(3, 0, 0, 0.66)
$outer_color = rgba(252, 105, 250, 1)
$font_color = rgba(254, 252, 255, 1)
$placeholder_color = rgba(254, 252, 255, 0.7)
$check_color = rgba(117, 101, 207, 1)
