# Background and foreground colors
background = #030000
foreground = #FEFCFF

# Standard colors
palette = 0=#030000
palette = 1=#ff2936
palette = 2=#7E81E1
palette = 3=#ff476e
palette = 4=#A398EE
palette = 5=#fc69fa
palette = 6=#7565CF
palette = 7=#FEFCFF

# Bright colors
palette = 8=#ae3a3a
palette = 9=#ff858c
palette = 10=#c6c8f4
palette = 11=#ffa3b6
palette = 12=#e9e6fc
palette = 13=#ffc2fe
palette = 14=#b2a8e8
palette = 15=#ffffff
