background            #030000
foreground            #FEFCFF

# black
color0  #030000
color8  #ae3a3a

# red
color1  #ff2936
color9  #ff858c

# green
color2  #7E81E1
color10 #c6c8f4

# yellow
color3  #ff476e
color11 #ffa3b6

# blue
color4  #A398EE
color12 #e9e6fc

# magenta
color5  #fc69fa
color13 #ffc2fe

#cyan
color6  #7565CF
color14 #b2a8e8

#white
color7  #FEFCFF
color15 #ffffff


